default: &default 
 adapter: postgresql 
 encoding: unicode 
 pool: 5 
 username: praktykant 
 password:

development: 
 <<: *default 
 database: training_development 

test: 
 <<: *default 
 database: training_test
